### ISSUE TITLE
Game crashing in multiplayer

### ISSUE THREAD

**Issue by jeinstei** [Kiplacon/Renai-Transportation#30]
I think there's something going on with ghost interactions. We're running 0.9.11, on 1.1.57 headless. It looks like there's a bad entity name floating around. Happy to debug futher with some guidance.

```
17236.687 Error MainLoop.cpp:1284: Exception at tick 1606749: The mod Renai Transportation (0.9.11) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event RenaiTransportation::RTInteract (ID 174)
Unknown entity name: characterRTGhostRTGhost
stack traceback:
[C]: in function 'create_entity'
__RenaiTransportation__/script/MiscFunctions.lua:23: in function 'SwapToGhost'
__RenaiTransportation__/script/event/interact.lua:233: in function <__RenaiTransportation__/script/event/interact.lua:1>
17236.687 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod Renai Transportation (0.9.11) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event RenaiTransportation::RTInteract (ID 174)
Unknown entity name: characterRTGhostRTGhost
stack traceback:
[C]: in function 'create_entity'
__RenaiTransportation__/script/MiscFunctions.lua:23: in function 'SwapToGhost'
__RenaiTransportation__/script/event/interact.lua:233: in function <__RenaiTransportation__/script/event/interact.lua:1>"
```

**Comment by jeinstei** [comment]
I'm guessing an easy fix would be to have swaptoghost return the original entity if the `.name` is already ending in `RTghost`, to avoid fast clicks

Something like `if OG.name:match("(.*)RTghost$") then return OG`. I can test it later to see if I can break it on my local install

https://github.com/Kiplacon/Renai-Transportation/blob/879b2f2d3047a88f669a3fff29603b032ab4c83b/script/MiscFunctions.lua#L19-L30

https://github.com/Kiplacon/Renai-Transportation/blob/879b2f2d3047a88f669a3fff29603b032ab4c83b/script/event/interact.lua#L227-L240

**Comment by Kiplacon** [comment]
It looks like the crash happens if you were to do 2 things at once that involve swapping to collision-immune version of the in game character. Your solution seems right, I should check first to make sure the character isn't already in "ghost mode" before trying to swap
