### ISSUE TITLE
Any interest in adding support for the Armored Train mod?

### ISSUE THREAD

**Issue by toranmallow** [Kiplacon/Renai-Transportation#31]
I tried out Renai Transportation in combination with the [Armored Train (Turret Wagons)](https://mods.factorio.com/mod/Armored-train) mod by [pandamiami80s](https://mods.factorio.com/user/pandamiami80s), and I noticed that after a train with any of its custom turret wagon types was launched and landed, the come back unloaded.  The basic armored locomotive engine unit lands with its full extended inventory of fuel intact, but the turret wagons land empty.

I looked at the code from Armored Train and Renai Transportation, and I think I see why this is happening.  Armored Trains turret wagons are defined as a copy of type cargo-wagon, but with their inventory_size set to 0.  The ammo for the turret is instead contained in a separate turret entity tied to the wagon it is on.  The normal landing code in Renai's trains/on_tick() doesn't know anything about this turret, so the new train it creates on landing doesn't inherit the ammo.

Would you have any interest in adding support for the Armored Train mod as an optional dependency in Renai?  I think the main impact would be to the part of the landing code quoted down below.  We'd need a few extra elseif cases for the Armored Train wagon types that are smart enough to look into the associated turret objects and copy their ammo.

```
		if (NewTrain.type == "locomotive") then
			NewTrain.color = properties.color
			NewTrain.backer_name = properties.SpecialName
			if (NewTrain.burner) then
				NewTrain.burner.currently_burning = properties.CurrentlyBurning
				NewTrain.burner.remaining_burning_fuel = properties.RemainingFuel
				for FuelName, quantity in pairs(properties.FuelInventory) do
					NewTrain.get_fuel_inventory().insert({name = FuelName, count = quantity})
				end
			end
		elseif (NewTrain.type == "cargo-wagon") then
			NewTrain.get_inventory(defines.inventory.cargo_wagon).set_bar(properties.bar)
			for i, filter in pairs(properties.filter) do
				NewTrain.get_inventory(defines.inventory.cargo_wagon).set_filter(i, filter)
			end
			for ItemName, quantity in pairs(properties.cargo) do
				NewTrain.get_inventory(defines.inventory.cargo_wagon).insert({name = ItemName, count = quantity})
			end
		elseif (NewTrain.type == "fluid-wagon") then
			for FluidName, quantity in pairs(properties.fluids) do
				NewTrain.insert_fluid({name = FluidName, amount = quantity})
			end
		elseif (NewTrain.type == "artillery-wagon") then
			for ItemName, quantity in pairs(properties.artillery) do
				NewTrain.get_inventory(defines.inventory.artillery_wagon_ammo).insert({name = ItemName, count = quantity})
			end
		end
```

**Comment by Kiplacon** [comment]
I'd definitely be down to add the compatibility, but how difficult it will be depends on how that extra turret works. Each mod can only affect its own things or things in the base game. In the base game, cargo wagons don't have connections to turrets, so if the only relationship between the armored cargo wagon and its turret is handled by the Armored Trains mod then I won't be able to do it all in my mod, there would have to be a change in Armored Trains too that will tell my mod about the connection between the cargo wagon and its turret.

I had to do something similar with Vehicle Wagons 2. It's a mod that lets you attach cars/tanks onto a train wagon. That's not something that exists in the base game so what happened was that after one of those wagons jumped, the new landed train didn't have the vehicle in it anymore. I had to colaborate with the mod's author to have our mods do the right exchange of info to put the old vehicle back into the new vehicle wagon.

I'll see how it works in the Armored Trains mod to see if we'd have to do something like that again.

**Comment by toranmallow** [comment]
Awesome!  I'm willing to help, if there's anything I can do.  I noticed that the source repo for Armored Trains had been emptied out, so I contacted pandamiami80s.  He's not doing anything with the mod currently, and he gave me permission to fork the code so that we could add to it to support the Renai integration.  I grabbed the code from his last release from the mod's zip file and imported it into Github.  It is available here: [https://github.com/toranmallow/Armored-train](https://github.com/toranmallow/Armored-train).  I was thinking it perhaps needs some helper functions to expose the turret related operations to Renai.

**Comment by Kiplacon** [comment]
So from the looks of it it does indeed store the link between wagon and turret in its own list. 
![image](https://user-images.githubusercontent.com/12401534/178379158-c2b9e500-3393-4c9f-acce-3bb332a6b14d.png)
Every tick it slides the turret towards the wagon if it's not right on top. 
So for compatibility to work what has to happen is:
1. At the time of the jump, my mod requests the turretPlatformList from Armored Trains, looks up which turret is linked to the wagon, and record what ammo is inside
2. At the time the train lands, my mod requests the turretPlatformList again and looks up the turret linked to the new wagon, and put the ammo back
The way to do this sharing of info is with this part of the API https://lua-api.factorio.com/latest/LuaRemote.html which I'm not really familiar with. For Vehicle Wagons 2 I just put in what the author asked for and it worked after, but it doesn't look too complicated.

**Comment by toranmallow** [comment]
Sounds at least possible.  I'll start looking through the Armored Train mod to see what it would take to add some remote calls we could use.  I'm still a little mystified about what happens between the association of a turret and a wagon when the train hits a ramp.  The wagon jumps, is deleted, and when it's time to hit the ground again, it's recreated.  But what happens to that turret associated with the wagon?  Seems like it would be left orphaned in the list of turrets, still out there, but with no association to a wagon.

**Comment by Kiplacon** [comment]
so it looks like the remote sending code can go pretty much anywhere in Armored Trains control.lua file. We'd just have to set it up so that it will send its global.turretPlatformList when my mod asks for it and in theory it should be good to go
like this

```
remote.add_interface("ArmoredTrains",
{
    SendTurretList = function()
        return global.turretPlatformList
    end
})
```
Then on my end as I'm rebuilding the trains I use
`list = remote.call("ArmoredTrains", "SendTurretList")`
and reference 'list' to get the turret on each wagon

**Comment by Kiplacon** [comment]
By the way do you know how to actually load the turrets with ammo? Clicking on it doesn't open it

**Comment by toranmallow** [comment]
Loading of the turrets is a little weird.  I usually throw down a chest and an inserter to load them.  Sometimes I find the inserters get stuck and I have to rotate them around a couple of times to get things loading.

I've pushed my forked copy of Armored-train, named Armored-train-renai, to the mod portal.  If you try it, be sure to get version 0.4.6 or higher.  My first version had some loading issues.

I added the remote interface code you listed to the mod, as well as enabled support for gvv with it by default.

[https://mods.factorio.com/mod/Armored-train-renai](https://mods.factorio.com/mod/Armored-train-renai)

**Comment by Kiplacon** [comment]
I think I got it working, I only have the changes here on github at the moment. If you download the 1.0.3 version along with your version of armored trains, the ammo retaining should work. Try it and let me know how it goes for you

**Comment by toranmallow** [comment]
Thank you, that appears to have fixed things.  I was able to run one of each of the turret wagon types past a jump and they came back with ammo (or fuel in the case of the radar turret).  Ship it!

**Comment by toranmallow** [comment]
Would you mind posting this new 1.0.3 version to the mod portal, please?  I'm about to start a new play through, and I'd like to have all my mods synced through the portal, if possible.

**Comment by Kiplacon** [comment]
Oh shoot I thought I did post it but I guess something failed. I'll upload it there now

**Comment by toranmallow** [comment]
Dope, thank you!  I was able to pull 1.0.3 from the portal.  I'd say you can close this issue.  Thank you for making this game even more fun with your mod!  Can't wait to see what other wackiness future updates might bring!
