### ISSUE TITLE
You may have accidentally replaced some files in the repo with the wrong mod

### ISSUE THREAD

**Issue by obfuscatedgenerated** [Kiplacon/Renai-Transportation#33]
In [927e7b1](https://github.com/Kiplacon/Renai-Transportation/commit/927e7b11224eca42588df729dcf5d03a20cd47c6), some files were replaced with reference to "FactoryPlanet" which doesn't seem right. Try git revert if this isn't right?

**Comment by obfuscatedgenerated** [comment]
Weirdly, version 1.0.5 on GitHub releases reflects this problem but the Factorio releases doesn't seem to.

**Comment by Kiplacon** [comment]
lol nice catch, I'll try and redo it. That's from an old mod folder I tried messing around with in the past

**Comment by Kiplacon** [comment]
I think it's all correct now
