### ISSUE TITLE
Logistic robots fulfil already completed orders upon disembarking zipline

### ISSUE THREAD

**Issue by obfuscatedgenerated** [Kiplacon/Renai-Transportation#35]
When a player leaves a zipline, robots all deliver items in the players logistic order, no matter if it is already at the maximum specified. If it is at the maximum, the robots deliver an item then take one.

It's resolved by turning personal logistics off and on again once you disembark. Perhaps this could be done from code?

**Comment by Kiplacon** [comment]
I think this was due to the fact that I forgot to transfer over logistics request/trash slots between going on/off the zipline. I added that in now and in my brief test it seems to help. Let me know if it works for you on the new version
