### ISSUE TITLE
Crash when trying to use Programmable Zipline Trolley

### ISSUE THREAD

**Issue by Marc-Harony** [Kiplacon/Renai-Transportation#37]
Hi !
The game crashes when we try to interract with a zipline controller.

Here's the crashlog : 
```Error while running event RenaiTransportation::RTClick (ID 176)
__RenaiTransportation__/script/GUIs.lua:79: attempt to index field 'preferences' (a nil value)
stack traceback:
	__RenaiTransportation__/script/GUIs.lua:79: in function 'ShowZiplineTerminalGUI'
	__RenaiTransportation__/script/event/click.lua:108: in function <__RenaiTransportation__/script/event/click.lua:3>```

**Comment by Kiplacon** [comment]
Looks like I had a conditional check set to AND instead of OR which may have been a problem if you are playing on a new joining a save for the first time with people who already had a world. Made a quick tweak and I think it should be fixed now on 1.1.8

**Comment by Marc-Harony** [comment]
Thanks, I check it and I keep you aware asap ! 🙏🏻

**Comment by Marc-Harony** [comment]
Everything's working fine ! Thanks !

**Comment by Kiplacon** [comment]
👌
