### ISSUE TITLE
Zipline Trolley left on cable after dismounting

### ISSUE THREAD

**Issue by octylFractal** [Kiplacon/Renai-Transportation#38]
This bug seems rare, but sometimes an zipline trolley will remain on the cable after dismounting from it. Removing the cable or re-loading the game doesn't fix this issue. The attached save file contains the broken trolley at [4.8, 16.8].

[RenaiTransportationBug.zip](https://github.com/Kiplacon/Renai-Transportation/files/9942984/RenaiTransportationBug.zip)

**Comment by octylFractal** [comment]
It did seem to disappear after a while. Not sure why.

**Comment by Kiplacon** [comment]
Hey, sorry I dont check github much. I had this problem reported before and it also eventually sorted itself out. I checked out your save and I still cant really find anything. Do you happen to remember how you dismounted the zipline and get the trolley stuck like that?

**Comment by octylFractal** [comment]
It was a manual dismount using the interact keybind. Nothing else special that I can remember, though it's possible I might have accidentally interacted with another pole simultaneously.

**Comment by Kiplacon** [comment]
Forgot this was here, I think this may have been linked to the multiplayer issue where zipline parts were not handled right when players disconnect. I havent seen any reports on something like this happening since so I'm gonna assume this is good
