### ISSUE TITLE
Unknown entity name: RTItemProjectile-deadlock-stack-salt18

### ISSUE THREAD

**Issue by CastaS** [Kiplacon/Renai-Transportation#43]
I get the following error:
 105.020 Error MainLoop.cpp:1288: Exception at tick 19774: The mod Renai Transportation (1.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RenaiTransportation::on_nth_tick(3)
Unknown entity name: RTItemProjectile-deadlock-stack-salt18
stack traceback:
	[C]: in function 'create_entity'
	__RenaiTransportation__/control.lua:283: in function <__RenaiTransportation__/control.lua:75>
 111.449 Quitting: user-quit.
 112.034 Goodbye

Tell me if you need the mod which is not on the modportal

[factorio-current.log](https://github.com/Kiplacon/RenaiTransportation/files/11471789/factorio-current.log)
[crash renai.zip](https://github.com/Kiplacon/RenaiTransportation/files/11471790/crash.renai.zip)

**Comment by Kiplacon** [comment]
It looks like the deadlock-stack-salt is causing the issue. What mod does it come from? I have an idea of what it might be, but I'd like to see how that item is coded

**Comment by CastaS** [comment]
the root object comes from Salt & chorine by brevven and i think deadlock's stacking beltboxes & compact loaders creates it dynamicly

**Comment by CastaS** [comment]
work with the placeholder graphics. i guess the mod load order has something to do with if i judge the changelog right.
