### ISSUE TITLE
Game does not starts with Krastio 2 and Bullet Tracers

### ISSUE THREAD

**Issue by GribanovIvan** [Kiplacon/Renai-Transportation#44]
"RenaiTransportation": __RenaiTransportation__/data-final-fixes.lua:778: attempt to index field 'action_delivery' (a nil value)
stack traceback:
        __RenaiTransportation__/data-final-fixes.lua:778: in main chunk
[factorio-current.log](https://github.com/Kiplacon/RenaiTransportation/files/12268320/factorio-current.log)

**Comment by Kiplacon** [comment]
idk if something changed but I just tried it and the game loads and plays with those mods installed, I shot a few nests and the bullet tracers worked

**Comment by GribanovIvan** [comment]
Confirming something changed. Something is got fixed
