### ISSUE TITLE
Inserter arrows are slightly offset compared to vanilla inserters

### ISSUE THREAD

**Issue by ZeShmoutt** [Kiplacon/Renai-Transportation#48]
See image below for reference. The thrower arrow should be just a tiny bit further.
![image](https://github.com/Kiplacon/RenaiTransportation/assets/36408045/b94804d6-c7ea-4849-8419-8c3f557b50b6)

**Comment by Kiplacon** [comment]
Holy moly what is this unplayable trash doctor we need a fix STAT

**Comment by Kiplacon** [comment]
Close one we should be good now thanks for the report m80

**Comment by ZeShmoutt** [comment]
It's funny because inserters that are already placed still have the offset, but new inserters are fine.
![image](https://github.com/Kiplacon/RenaiTransportation/assets/36408045/5a524d50-eb89-450c-a068-ed83d897048c)
Ah well, not a big deal, this base is supposed to be torn down sooner or later.

**Comment by Kiplacon** [comment]
lol you know what you're totally right, I forgot that it wouldn't apply retroactively 😅. But yeah it should function the same either way and works for new ones so I'm not too miffed, I'm not sure how I would even adjust all existing thrower inserters anyway
